version: '3'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
        restart: always
 
    repo1 :
        depends_on:
            - reverseproxy
        image: repo1
        container_name: repo1
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf    

    back-repo1:
        depends_on:
            - reverseproxy
        image: back-repo1
        container_name: back-repo1
        restart: always
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: repo1
            MYSQL_USER: repo1
            MYSQL_PASSWORD: 12345
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306