version: '3'

services:
    repo1 :
        depends_on:
            - back-repo1
        build: ./repo1
        container_name: repo1
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./repo1/dist:/usr/share/nginx/html

    back-repo1:
        depends_on:
            mysql:
                condition: service_healthy
        build: ./back-repo1
        container_name: back-repo1
        restart: unless-stopped
        volumes:
            - ./back-repo1:/usr/src/app
            
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: repo1
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3306"]
            interval: 10s
            timeout: 10s
            retries: 10